REPLACE INTO cscart_payment_processors (`processor`,`processor_script`,`processor_template`,`admin_template`,`callback`,`type`) VALUES ('Everypay','everypay.php', 'views/orders/components/payments/cc_outside.tpl','everypay.tpl', 'Y', 'P');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','public_key','Public Key');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','secret_key','Private Key');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','test_mode','Test Mode');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','installments','Installments');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','text_evp_failed_order','No response from Everypay has been received. Please contact the store staff and tell them the order ID:');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','text_evp_pending','Payment failed! Please check EveryPay dashboard using Payment Token ');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EN','text_evp_success','Payment Sucessful. You can check the payment under Payments on Everypay dashboard. ');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','public_key','Δημόσιο Κλειδί');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','secret_key','Ιδιωτικό Κλειδί');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','test_mode','Δοκιμαστική Λειτουργία');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','installments','Δόσεις');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','text_evp_failed_order','Καμία απάντηση από την Everypay. Παρακαλώ επικοινωνήστε με τα κεντρικά γραφεία της εταιρείας και δώστε τους τον κωδικό παραγγελίας: ');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','text_evp_pending','Η συναλλαγή απέτυχε! Παρακαλώ ελέγξτε την πληρωμή στον λογαριαμό σας στο Everypay dashboard χρησιμοποιώντας τον κωδικό πληρωμής ');
REPLACE INTO cscart_language_values (`lang_code`,`name`,`value`) VALUES ('EL','text_evp_success','Επιτυχής πληρωμή. Μπορείτε να ελέγξτε την πληρωμή στον λογαριαμό σας στο Everypay dashboard. ');